// GENERATED by scripts/sync-deployments.mjs — do not edit by hand.
// Source: packages/deployments/<chainId>.json (written by a forge deploy).
// Regenerate after every redeploy, then publish a new SDK version.
import type { RallyAddresses } from "./types";

export const DEPLOYMENTS: Record<number, RallyAddresses> = {
  4663: {
    chainId: 4663,
    deploymentBlock: 39900646,
    weth: "0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73",
    usdc: "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168",
    poolManager: "0x8366a39CC670B4001A1121B8F6A443A643e40951",
    paramRegistry: "0xb1d3E3da00D1089D35a9FC2A309931405A99CBDB",
    launchLib: "0x5ab19e16e1196642D89243d2910B4c9045E9A5cD",
    launchHook: "0x729Db85927D09eFa42fec9cD6B7Ab85d47Ae28CC",
    rallyFactory: "0xF29662C90741B801e6A19Af87c195a74933B9638",
    rallyRouter: "0xafA09a416B2DD1F6b8bdAA7A11e499F6b13AFdd5",
    dividendDistributor: "0x6000908180132982AA17a4D7C2418a58FD0d4e0a",
    rallyVault: "0x6770Cf9EccA6D1C6060951f8F75507544CBA88F7",
    gachaVault: "0x365be759C7A5a7567637626b6b4f4c9a0e648abE",
    legacyDeployments: [
      {
        launchHook: "0x38545dDedD7b1Af79685aF76F4369Bf1A8f928cc",
        rallyFactory: "0xB7bC50cc3531C455A6f63530Eab55f87aDe7CE90",
        rallyRouter: "0x65FcbF2165B4D80e004c39389d3EcAc09AE0A620",
        paramRegistry: "0x5bd485A3059D459eA6D6DFd49fE7a2Ff2Af67C11",
        launchLib: "0xE8e91C2c0A8F49Dd0Aecb0177b7184e4aBAC8B41",
        rallyVault: "0xD45D5BeC4548CBd7624487Dd9e342058b9bD8107",
        dividendDistributor: "0xB279a18fAa3f5a547F1ECb45C460293823beE7D2",
        gachaVault: "0xE6b0a41Dd25Ea61A733a9F5271Af807128ea4986",
        deploymentBlock: 34719118,
      },
    ],
  },
  11155111: {
    chainId: 11155111,
    deploymentBlock: 11513971,
    weth: "0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14",
    usdc: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238",
    poolManager: "0xE03A1074c86CFeDd5C142C4F04F1a1536e203543",
    paramRegistry: "0xE8e91C2c0A8F49Dd0Aecb0177b7184e4aBAC8B41",
    launchLib: "0xF73f988e488453Fb304EF33b1340F55CFCbe8409",
    launchHook: "0xea58145B56fFd783EAC91b7bD75e75fa643c28Cc",
    rallyFactory: "0xC731D1Da32C05e5031AAa95bDc075A2af5E66433",
    rallyRouter: "0xB279a18fAa3f5a547F1ECb45C460293823beE7D2",
    dividendDistributor: "0xE1F1e2890CA088e08662D2344FD8391105C4e531",
    rallyVault: "0x5bd485A3059D459eA6D6DFd49fE7a2Ff2Af67C11",
    gachaVault: "0x937a1EDBff87165850F848F9F377D1Aa4611ba91",
  },
};
